# Generated by Django 3.1.1 on 2020-10-03 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('artist', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=250)),
                ('logo', models.ImageField(upload_to='album_images')),
                ('date_uploaded', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mixtape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mixtape_title', models.CharField(max_length=250)),
                ('mixtape_artist', models.CharField(max_length=250)),
                ('mixtape_logo', models.ImageField(upload_to='Mixtape_images')),
                ('mixtape_date_uploaded', models.DateField()),
                ('mixtape_audiofile', models.FileField(upload_to='Mixtape_songs')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_title', models.CharField(max_length=250)),
                ('Video_artist', models.CharField(max_length=250)),
                ('Video_url', models.URLField()),
                ('Video_logo', models.ImageField(upload_to='Video_images')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=250)),
                ('song_artist', models.CharField(max_length=250)),
                ('song_logo', models.ImageField(upload_to='albumsong_images')),
                ('song_audiofile', models.FileField(upload_to='album_songs')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album')),
            ],
        ),
    ]
