# Generated by Django 3.1.1 on 2020-10-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='gallery_images')),
            ],
        ),
    ]
