# Generated by Django 3.1.1 on 2020-10-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
